[tool.poetry]
name = "document-segmentation"
version = "0.1.0"
description = ""
authors = ["Carsten Schnober <c.schnober@esciencecenter.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"
pagexml-tools = "^0.4.2"
openpyxl = "^3.1.2"
torch = "^2.2.0"
torchvision = "^0.17.0"
torchaudio = "^2.2.0"
transformers = "^4.38.2"
scikit-learn = "^1.3.2"
torcheval = "^0.0.7"
pydantic = "^2.5.3"
sentence-transformers = "^2.5.1"


[tool.poetry.group.dev.dependencies]
ruff = "^0.3.0"
pre-commit = "^3.6.0"
pytest-cov = "^4.1.0"
requests-mock = "^1.11.0"
pytest = "^8.0.2"
ipykernel = "^6.29.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
"extend-select" = ["I"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
