name: Build and Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
         # FIXME windows-latest, see: https://github.com/LAHTeR/document_segmentation/actions/runs/7250392510/job/19750467453
         # FIXME using macos-13 instead of macos-latest because macos >= 14 does not support Python 3.9
        os: [ubuntu-latest, macos-13, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Setup a local Poetry virtual environment
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - name: Install the project dependencies
        run: poetry install
      - name: Python tests
        run: poetry run pytest -v --cov document_segmentation/
