name: Ruff
on:
    pull_request:
      branches: [main]
    push:
      branches: [main]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: --ignore I001
